services:
  db:
    image: postgres
    container_name: feitio_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432

volumes:
  postgres_data:
