# Generated by Django 5.2 on 2025-04-26 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bands/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Bands',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('html_icon', models.CharField(help_text="Ex: <i class='bi bi-instagram'></i>", max_length=100)),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.CreateModel(
            name='BandSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.band')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialnetwork')),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='social_networks',
            field=models.ManyToManyField(related_name='redes_sociais', through='base.BandSocialNetwork', to='base.socialnetwork'),
        ),
    ]
