# Generated by Django 5.2 on 2025-06-08 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='social_networks',
            field=models.ManyToManyField(related_name='bands', through='base.BandSocialNetwork', to='base.socialnetwork'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='html_icon',
            field=models.CharField(help_text="Ex: i class='bi bi-instagram'> i", max_length=100),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.band')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='FeitioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feitio_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feitio Profile',
                'verbose_name_plural': 'Feitio Profiles',
            },
        ),
        migrations.CreateModel(
            name='BandFeitioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.band')),
                ('feitio_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feitioprofile')),
            ],
            options={
                'unique_together': {('feitio_profile', 'band')},
            },
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', through='base.BandFeitioProfile', to='base.feitioprofile'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('main_description', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='releases/')),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='base.band')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='ReleaseCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('crew', models.TextField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='base.release')),
            ],
            options={
                'verbose_name': 'Release Credit',
                'verbose_name_plural': 'Release Credits',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='base.band')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data do show')),
                ('city', models.CharField(default='', help_text='Cidade onde o show ocorrerá. Ex: São Paulo', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='Estado onde o show ocorrerá (pode deixar em branco). Ex: SP', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='País onde o show ocorrerá. Ex: Brasil', max_length=100, null=True)),
                ('venue', models.CharField(help_text='Local onde o show ocorrerá. Ex: Espaço das Américas', max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='base.tour')),
            ],
            options={
                'verbose_name': 'Concert',
                'verbose_name_plural': 'Concerts',
            },
        ),
    ]
