# Generated by Django 5.2 on 2025-04-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_band_info_contact_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='info_contact_booking',
        ),
        migrations.RemoveField(
            model_name='band',
            name='info_contact_copyright',
        ),
        migrations.RemoveField(
            model_name='band',
            name='info_contact_press',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data do show')),
                ('city', models.CharField(default='', help_text='Cidade onde o show ocorrerá. Ex: São Paulo, SP', max_length=100)),
                ('country', models.CharField(blank=True, help_text='País onde o show ocorrerá. Ex: Brasil', max_length=100, null=True)),
                ('venue', models.CharField(help_text='Local onde o show ocorrerá. Ex: Espaço das Américas', max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts', to='base.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.band')),
            ],
        ),
    ]
