# Generated by Django 5.2 on 2025-06-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
