# Generated by Django 5.2 on 2025-06-15 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_newslettersubscriber_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='band',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to='bands/', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='band',
            name='spotify_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para Spotify'),
        ),
        migrations.AlterField(
            model_name='band',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para vídeo'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_description',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='posts/', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='release',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='base.band', verbose_name='Banda'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.ImageField(upload_to='releases/', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='release',
            name='spotify_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para Spotify'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='release',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para vídeo'),
        ),
        migrations.AlterField(
            model_name='releasecredits',
            name='crew',
            field=models.TextField(verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='releasecredits',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Ano'),
        ),
    ]
