# Generated by Django 5.2 on 2025-04-26 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_concert_options_concert_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='band',
            name='social_networks',
            field=models.ManyToManyField(related_name='bands', through='base.BandSocialNetwork', to='base.socialnetwork'),
        ),
        migrations.CreateModel(
            name='FeitioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feitio_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Profile',
                'verbose_name_plural': 'Custom Profiles',
            },
        ),
        migrations.CreateModel(
            name='BandFeitioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.band')),
                ('feitio_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feitioprofile')),
            ],
            options={
                'unique_together': {('feitio_profile', 'band')},
            },
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', through='base.BandFeitioProfile', to='base.feitioprofile'),
        ),
    ]
