# Generated by Django 5.2 on 2025-04-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_contact_options_alter_band_social_networks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feitioprofile',
            options={'verbose_name': 'Feitio Profile', 'verbose_name_plural': 'Feitio Profiles'},
        ),
    ]
