# Generated by Django 5.2 on 2025-06-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
