# Generated by Django 5.2 on 2025-06-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_user_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
