# Generated by Django 5.2 on 2025-04-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_feitioprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('video_link', models.URLField(blank=True, null=True)),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='base.band')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='ReleaseCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('crew', models.TextField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='base.release')),
            ],
            options={
                'verbose_name': 'Release Credit',
                'verbose_name_plural': 'Release Credits',
            },
        ),
    ]
