# Generated by Django 5.2 on 2025-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_release_releasecredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_imge',
            field=models.ImageField(blank=True, null=True, upload_to='releases/'),
        ),
    ]
