# Generated by Django 5.2 on 2025-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_release_release_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
