# Generated by Django 5.2 on 2025-06-12 00:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_band_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
