# Generated by Django 5.2 on 2025-04-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_release_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
