# Generated by Django 5.2 on 2025-06-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_newslettersubscriber_unsubscribe_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='release',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
