# Generated by Django 5.2 on 2025-06-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_band_email_sent_band_published_at_post_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='release',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
