# Generated by Django 5.2 on 2025-04-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_release_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='release_imge',
            new_name='image',
        ),
    ]
