# Generated by Django 5.2 on 2025-06-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_band_slug_post_slug_release_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
