# Generated by Django 5.2 on 2025-06-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to='bands/', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='band',
            name='spotify_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para Spotify'),
        ),
        migrations.AlterField(
            model_name='band',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para vídeo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_description',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='posts/', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='release',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='base.band', verbose_name='Banda'),
        ),
        migrations.AlterField(
            model_name='release',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='release',
            name='image',
            field=models.ImageField(upload_to='releases/', verbose_name='Imagem principal'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(verbose_name='Data de lançamento'),
        ),
        migrations.AlterField(
            model_name='release',
            name='spotify_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para Spotify'),
        ),
        migrations.AlterField(
            model_name='release',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='release',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link para vídeo'),
        ),
    ]
