# Generated by Django 5.2 on 2025-06-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feitioprofile',
            name='profile_image',
        ),
    ]
