# Generated by Django 5.2 on 2025-06-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_band_description_alter_band_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.CharField(default='', help_text='Cidade onde o show ocorrerá. Ex: São Paulo', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='country',
            field=models.CharField(blank=True, help_text='País onde o show ocorrerá. Ex: Brasil', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(help_text='Data do show', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='state',
            field=models.CharField(blank=True, default='', help_text='Estado onde o show ocorrerá (pode deixar em branco). Ex: SP', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(help_text='Local onde o show ocorrerá. Ex: Espaço das Américas', max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='releasecredits',
            name='crew',
            field=models.TextField(verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='releasecredits',
            name='role',
            field=models.CharField(help_text='Ex: Produção, Mixagem...', max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='year',
            field=models.CharField(help_text='Ano da turnê', max_length=4, verbose_name='Ano'),
        ),
    ]
