# Generated by Django 5.2 on 2025-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_concert_city_alter_concert_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='releasecredits',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Ano'),
        ),
    ]
