"""
Django settings for gueersh_project project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.contrib import messages

load_dotenv()  # loads the configs from .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv("DEBUG"))

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   # Para desenvolvimento, exibe os emails no console

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base.apps.BaseConfig',   #app criado para o site base
    
    # Aplicativos do Django Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    #'allauth.socialaccount',
    #'allauth.socialaccount.providers.facebook',
    #'allauth.socialaccount.providers.google',
    
    'django_summernote',   #Editor de texto enriquecido para os posts
    
    'crispy_forms',  #Para formulários mais bonitos e funcionais
    'crispy_bootstrap5',  #Para usar o Bootstrap 5 com o Crispy Forms
]

#Configurações do Crispy Forms:
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",)
CRISPY_TEMPLATE_PACK = "bootstrap5"


SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    "allauth.account.middleware.AccountMiddleware",

    'base.middleware.ClearMessagesInAdminMiddleware',   #Middleware personalizado para limpar mensagens no admin
]



ROOT_URLCONF = 'gueersh_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gueersh_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE", 'django.db.backends.postgresql_psycopg2'),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Configurações do Django Allauth
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


#Configurações do Django Allauth:
LOGIN_REDIRECT_URL = '/'  # URL para redirecionar após o login
LOGOUT_REDIRECT_URL = '/'  # URL para redirecionar após o logout
ACCOUNT_LOGOUT_ON_GET = True    # Permite logout via GET request (não precisa ter página de logout)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Método de autenticação (pode ser username, email ou ambos)

ACCOUNT_EMAIL_VERIFICATION = "mandatory"   #Faz com que o email precise ser verificado antes de permitir o login
ACCOUNT_CONFIRM_EMAIL_ON_GET = True  #Confirma ao clicar no link, sem botão extra
ACCOUNT_SESSION_REMEMBER = False #Desabilita a opção de lembrar a sessão (não armazena cookies de sessão) 
ACCOUNT_UNIQUE_EMAIL = True  #Garante que o email seja único (não pode haver dois usuários com o mesmo email)
#ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 0.0007  #Teste rápido de expiração do email de confirmação (1 minuto)

#Formulários personalizados:
ACCOUNT_FORMS = {
    'signup': 'base.forms.CustomSignupForm',  # ajuste para seu app
}


#Configurações do Summernote:
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']],
            ['table', ['table']],
            ['insert', ['picture', 'link', 'video', 'hr']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
        'width': '100%',
        'height': '500px',
    },
}


MESSAGE_TAGS = {
    messages.ERROR: 'danger',  # transforma 'error' em 'danger'
}

#Configurações de email
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

#Configurações do site
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")  # URL do site, usada para links em emails

